
# Site settings

url: "http://AlphaMyk.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: http://AlphaMyk.github.io

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "alphamyk"
lang: "en"
title: "AlphaMyk"
favicon: "/img/favicon.ico"
description: "Site to play around with"
keywords: "griffith, michael, griff, alphamyk"

################
# Intro layout #
################

black-favicon: "/img/crest_sm.png"
background-img: "../img/intro-bg.jpg"
me-img: "/img/griff.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: False  # Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "We're no strangers to love"
  - text: "You know the rules and so do I"
  - text: "A full commitment's what I'm thinking of"
  - text: "You wouldn't get this from any other guy"
  - text: "I just wanna tell you how I'm feeling"
  - text: "Gotta make you understand"
  - text: "Never gonna give you up"
  - text: "Never gonna let you down"
  - text: "Never gonna run around and desert you"
  - text: "Never gonna make you cry"
  - text: "Never gonna say goodbye"
  - text: "Never gonna tell a lie and hurt you"
  - text: "We've known each other for so long"
  - text: "Your heart's been aching, but"
  - text: "You're too shy to say it"
  - text: "Inside, we both know what's been going on"
  - text: "We know the game and we're gonna play it"
  - text: "And if you ask me how I'm feeling"
  - text: "Don't tell me you're too blind to see"
  - text: "Never gonna give you up"
  - text: "Never gonna let you down"
  - text: "Never gonna run around and desert you"
  - text: "Never gonna make you cry"
  - text: "Never gonna say goodbye"
  - text: "Never gonna tell a lie and hurt you"
  - text: "Never gonna give you up"
  - text: "Never gonna let you down"
  - text: "Never gonna run around and desert you"
  - text: "Never gonna make you cry"
  - text: "Never gonna say goodbye"
  - text: "Never gonna tell a lie and hurt you"
  - text: "(Ooh, give you up)"
  - text: "(Ooh, give you up)"
  - text: "Never gonna give, never gonna give"
  - text: "(Give you up)"
  - text: "Never gonna give, never gonna give"
  - text: "(Give you up)"
  - text: "We've known each other for so long"
  - text: "Your heart's been aching, but"
  - text: "You're too shy to say it"
  - text: "Inside, we both know what's been going on"
  - text: "We know the game and we're gonna play it"
  - text: "I just wanna tell you how I'm feeling"
  - text: "Gotta make you understand"
  - text: "Never gonna give you up"
  - text: "Never gonna let you down"
  - text: "Never gonna run around and desert you"
  - text: "Never gonna make you cry"
  - text: "Never gonna say goodbye"
  - text: "Never gonna tell a lie and hurt you"
  - text: "Never gonna give you up"
  - text: "Never gonna let you down"
  - text: "Never gonna run around and desert you"
  - text: "Never gonna make you cry"
  - text: "Never gonna say goodbye"
  - text: "Never gonna tell a lie and hurt you"
  - text: "Never gonna give you up"
  - text: "Never gonna let you down"
  - text: "Never gonna run around and desert you"
  - text: "Never gonna make you cry"
  - text: "Never gonna say goodbye"
  - text: "Never gonna tell a lie and hurt you"


########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "AlphaMyk"

###############
# Life Events #
###############

events:
  - image: "/img/life/suse.jpg"
    date: "April 2014 - Today"
    description: "Developer, SUSE Linux guy, and IT Engineer"
  - image: "/img/life/oops.jpg"
    date: "March 2008 - April 2014"
    description: "Began the life of a timelord (SCM Engineer)"
  - image: "/img/life/wedding.jpg"
    date: "September 2007"
    description: "Got hitched!"
  - image: "/img/life/cow.jpg"
    date: "In the year 2000 - Sometime in 2007"
    description: "Dead-end jobs and more schooling"
  - image: "/img/life/bringiton.png"
    date: "September 1998 - December 1999"
    description: "SDSU and movie stardom ;)"
  - image: "/img/life/gwj.jpg"
    date: "September 1996 - June 1998"
    description: "GreenWater Jazz swung onto the scene"
  - image: "/img/life/stork.png"
    date: "October 1980"
    description: "Born, at a very early age"

# First image of the Life timeline
life-img: "/img/life/toonmehead.png"

##################
# Social layout #
##################

email: "myk@alphamyk.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "http://facebook.com/alphamyk"
  - title: "twitter"
    url: "http://twitter.com/alphamyk"
  - title: "youtube"
    url: "http://youtube.com/emperormykel"
  - title: "github"
    url: "https://github.com/AlphaMyk"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Life: 'life'
  Social: 'social'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
